language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
services:
- postgresql
deploy:
  api_key:
    secure: PdfESdsTXiHtAdfh9kUe/VgiH3tfg9meeUEB3lhPVbkTQCLyNr8Y5uFVUpwpnhDp7DuhJqQ+/rovwp+ytQ5ridoyq2oUH2+ORPWU3ft7lKn3/Yaan6yu+0Q7R7gyRHStoSoJOLyDenWc8pQpjkekSD1kUzgA+rqTXI4saSIALR7tuX6Om/o+GfyofHuSBRwvdgLrkUXkdDd0tm3dU0T0r1K+M/6VEbY9tHi/oo+/h2NMj/fzsyGrO1d+4cIMRG+Rr8FzSBop2zPyvKk47M/1EwcQoZ8/TjMfs700hOL1SLwLxFpvFmJmyVNz93LeL7/lUfhcJXjeJnm5RefzxM5UetnFW6Dg4IwOekuhPzEi8QieZBjwzbC3I8N7R9E/ZDUg6HS2KMzaL8MNZVAE+KOAqz3aiMzUC/r/IhblQag6fNJBdeDEDHCPYSIXJCt/kJ9nzE0IW9cNNoaWh1INmq+lVzcvsWBnfa5P59jKNm/NZWfhoPmXWKFo4wAuXqO8XsyfmoOh5Fx4zJMARxIYry+KsSonxqBKQHrbRB+J9cEw2J6ZsVKw3e84IqTY4LW2Cwfkd6CpU7i/pdhq9gxtxHcthqO946fQe9lIinlJSbEUztMFwjqIOzzzRj/40t5IIJdFkJMrwYngHNZFnFBps4v7p57LcLR8xbn+O6as6neXCrU=
  app: fore-finder-be
  on:
    repo: foreFinder/fore-finder-be
    branch: main
    cleanup: 'true'
