language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: GrvZnSkY8n+PDM5RBUQPVRhV0O3AiPril1H8wUxr8KjVhajxSV8pa5bVoKxTZerLLSBhuP8M6qr6a5CDG1gvCt+ooLZWreH8KMKi6tu4mKpja3YdKb5+BnKsZed8hTkMbwd7j0ghfxvQdx+XSZFz/IoMM0BHM0ed1MZLxT8H0Dr8cbRBSHaXDpVK2Ku2ELxO3kKkISyVGz+LPthG7iLoyUP9i4begtzeaqEIOhUUdYtwQq72pdBjIvvaqAAbvPMyd/NvUbgGne8YdzvQRwVud8SkEXLkcSPAufVsPgECytKWwY+0LfCFocW6ouzH1eVfmGrBeHmscN1QAhJTzt8GTQ5krk8bIk8KYM7EQfA87uw/01cGzjdSwjRUKgOldtL5nAVN/mXdQoYtW0J+y8UfxcsIvt4sAXCnLpFt9qZmZRwrPRlVPEDaotAgWquIMDHjGqnZ473iUPg15uTEI/NroJ0Fx8jkcBrUtJwiXjayfJAYjnNfXw+pihv2QrlhBOuZOQYPvCNdjL06PiSWpiDhKj11uhq/L2tv3Bp/Rcpr9JKG8FQOF9fkXWR91ExTHUZ/gB+2WoWI5Oc1uU2/iltQ/13mlKmbU28EFhLC6d69fW9S9mQK0zcTVuIpOeb4kTf7942EWrK64EEjJGwhKEUY8F1UK18xFn94qjPX3BFGTvc=
  app: fore-finder-be
  on:
    repo: foreFinder/fore-finder-be
    branch: main
  skip_cleanup: 'true'
